name: Lint Helm Charts

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check base branch
      if: github.event_name == 'pull_request'
      run: |
        if [[ "${{ github.event.pull_request.base.ref }}" != "dev" ]]; then
          echo "Pull requests can only be merged from 'dev' to 'main'."
          exit 1
        fi

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.14.0'

    - name: Lint Helm Charts
      run: |
        helm lint .
